version: "3.7"

services: 
    web: 
        build: .
        command: sh -c "python manage.py makemigrations && 
                        python manage.py migrate &&
                        python manage.py runserver 0.0.0.0:8000"
        ports: 
            - 8000:8000
        env_file: 
            - ./env.dev
        depends_on: 
            - db 
    db: 
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=admin 
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=dev 
    pgadmin: 
        image: dpage/pgadmin4 
        ports: 
            - 5555:80 
        environment: 
            - PGADMIN_DEFAULT_EMAIL: admin@admin.org 
            - PGADMIN_DEFAULT_PASSWORD: admin 
        restart: unless-stopped 
        depends_on: 
            - db 

volumes: 
    postgres_data:
